/**
 * @file bgmsg.h
 * This file contains message ids and messages generated by syncagent,
 * BG API error codes and error messages and other constants and strings
 * used by BG API.
 * @see bgsync.h
 */

/**
 * BG API uses parametrized error messages, hence you will see
 * placeholders like %c, %d,%ld, %x, %s embedded inside error messages.
 * They stand for values placed in error message when error occurs.
 * They are analogous to printf formatting specifications.
 */

/**
 * Information messages (messages of type BG_MSG_TYPE_INFO).
 * @see Message types in bgsync.h
 * @see bgMsg in bgsync.h
 */

#define BG_MSG_AGENT_STARTED				12000 /* Sync agent has been started */

#define BG_MSG_AGENT_STOPPED				12001 /* Sync agent has been stopped */

#define BG_MSG_AGENT_PAUSED					12002 /* Sync agent has been paused */

#define BG_MSG_AGENT_RESUMED				12003 /* Sync agent has been resumed */

#define BG_MSG_COMPOSE_STARTED				12004 /* Compose of priority %d has started for database \"%s\" */

#define BG_MSG_COMPOSE_FINISHED				12005 /* Compose of priority %d has finished for database \"%s\" */

#define BG_MSG_SYNC_STARTED					12006 /* Sync of priority %d has started for publications \"%s\" */

#define BG_MSG_SYNC_FINISHED				12007 /* Sync of priority %d has finished for publications \"%s\" */

#define BG_MSG_APPLY_STARTED				12008 /* Apply has started for database \"%s\" */

#define BG_MSG_APPLY_FINISHED				12009 /* Apply has finished for database \"%s\" */

#define BG_MSG_SERVER_NOTIFICATION			12010 /* Server notification of priority %d has been received for publication \"%s\" */

#define BG_MSG_NETWORK_CHANGED				12011 /* Network has changed from \"%s\" to \"%s\" */

#define BG_MSG_NO_NETWORK					12012 /* No network */

#define BG_MSG_NETWORK_EVAL                 12013 /* Evaluated network, name: "\%s\", speed: %ld bps, ping: %ld ms */

#define BG_MSG_TRACE                        12014 /* Trace message: %s */

#define BG_MSG_UNKNOWN_VALUE                12015 /* Unknown */

/**
 * Warning messages (messages of type BG_MSG_TYPE_WARNING).
 * @see Message types in bgsync.h
 * @see bgMsg in bgsync.h
 */

#define BG_MSG_BATTERY_LOW					12200 /* Battery power is low (%d %%) */

#define BG_MSG_MEMORY_LOW					12201 /* Memory is low (%ld bytes available) */

/**
 * Sync Agent control command strings.
 * @see Sync Agent control command codes in bgsync.h
 */

#define BG_CTRL_MSG_START					12300 /* Start */

#define BG_CTRL_MSG_STOP					12301 /* Stop */

#define BG_CTRL_MSG_PAUSE					12302 /* Pause */

#define BG_CTRL_MSG_RESUME					12303 /* Resume */

#define BG_CTRL_MSG_SHOW_UI					12304 /* Show UI */

#define BG_CTRL_MSG_HIDE_UI					12304 /* Hide UI */

/**
 * Sync Agent status name strings.
 * @see status codes in bgsync.h
 */

#define BG_STATUS_MSG_STOPPED				12400 /* Stopped */

#define BG_STATUS_MSG_START_PENDING			12401 /* Start Pending */

#define BG_STATUS_MSG_RUNNING				12402 /* Running */

#define BG_STATUS_MSG_PAUSE_PENDING			12403 /* Pause Pending */

#define BG_STATUS_MSG_PAUSED				12404 /* Paused */

#define BG_STATUS_MSG_RESUME_PENDING		12405 /* Resume Pending */

#define BG_STATUS_MSG_STOP_PENDING			12406 /* Stop Pending */

#define BG_STATUS_MSG_DEFUNCT				12407 /* Defunct */

/**
 * Sync state name strings.
 * @see bgSyncStatus in bgsync.h
 */

#define BG_SYNC_STATE_MSG_IDLE				12500 /* Idle */

#define BG_SYNC_STATE_MSG_PREPARE			12501 /* Prepare */

#define BG_SYNC_STATE_MSG_SEND				12502 /* Send */

#define BG_SYNC_STATE_MSG_RECEIVE			12503 /* Receive */

#define BG_SYNC_STATE_MSG_PROCESS			12504 /* Process */

/**
 * Error messages.  This section includes both message ids and messages
 * of type BG_MSG_TYPE_ERROR and BG API error codes and messages because of
 * interoperation between syncagent error messages and BG API errors.
 * @see bgError in bgsync.h
 * @see Message types in bgsync.h
 * @see bgMsg in bgsync.h
 */

#define BG_ERR_COMPOSE						-12500 /* Compose of priority %d has failed for database \"%s\" (see the cause) */

#define BG_ERR_SYNC							-12501 /* Sync of priority %d has failed for publications \"%s\" (see the cause) */

#define BG_ERR_APPLY						-12502 /* Apply has failed for database \"%s\" (see the cause) */

#define BG_ERR_RULE_LOAD					-12503 /* Could not load rule \"%s\" for publication \"%s\" (see the cause) */

#define BG_ERR_RULE_EVAL					-12504 /* Failed to evaluate rule \"%s\" for publication \"%s\" */

#define BG_ERR_NET_MANAGER					-12505 /* Network manager error has occured (see the cause) */

#define BG_ERR_PWR_MANAGER					-12506 /* Power manager error has occured (see the cause) */

#define BG_ERR_INTERNAL						-12507 /* Internal error has occured (the cause may have more information) */

#define BG_ERR_PLAT_RULE_IN_NON_PLAT_DB		-12508 /* Found platform rule \"%s\" in non-platform database \"%s\" */

#define BG_ERR_NET_AUTODIAL					-12509 /* Failed to establish dialup connection (see the cause) */

#define BG_ERR_SERVER_NOTIFICATION			-12510 /* Failed to process server notification of priority %d for publication \"%s\" (see the cause) */

#define BG_ERR_CONTROL_CONNECTION			-12511 /* Control connection to the agent is closed due to an error (see the cause) */

#define BG_ERR_INVALID_COMMAND				-12512 /* Invalid control command received: %d */

#define BG_ERR_INVALID_SERVER_NOTIFICATION	-12513 /* Invalid server notification received: \"%s\" */

#define BG_ERR_ACTIVE_CONNECTIONS			-12514 /* Cannot stop the agent because %d active connection(s) are present */

#define BG_ERR_CANNOT_ACCEPT_CTRL			-12516 /* The agent cannot accept control command \"%s\" because it is in state \"%s\" */

#define BG_ERR_PLATFORM_DB_NOT_FOUND		-12517 /* Could not find platform database */

#define BG_ERR_INVALID_RULE_TYPE			-12518 /* Invalid rule type: \"%s\" */

#define BG_ERR_INVALID_RULE_SUBTYPE			-12519 /* Invalid rule subtype: \"%s\" */

#define BG_ERR_INVALID_RULE_CLASS			-12520 /* Invalid rule class: \"%s\" */

#define BG_ERR_INVALID_RULE_SUBTYPE_TYPE	-12521 /* Invalid rule subtype \"%s\" for rule type \"%s\" */

#define BG_ERR_INVALID_DATE_FORMAT			-12522 /* Invalid date format: \"%s\" */

#define BG_ERR_INVALID_EVENT_SUBTYPE		-12523 /* Invalid subtype \"%s\" for an event rule */

#define BG_ERR_INVALID_COND_SUBTYPE			-12524 /* Invalid subtype \"%s\" for a condition rule */

#define BG_ERR_INVALID_EVENT_TYPE			-12525 /* Invalid type \"%s\" for an event rule */

#define BG_ERR_INVALID_COND_TYPE			-12526 /* Invalid type \"%s\" for a condition rule */

#define BG_ERR_MISSING_QUERY				-12527 /* Query is missing for a SQL rule */

#define BG_ERR_DUPLICATE_PLATFORM_DB		-12528 /* Found duplicate platform databases: \"%s\" and \"%s\" */

#define BG_ERR_ANOTHER_INSTANCE				-12529 /* Cannot start sync agent because another instance is already running */

#define BG_ERR_UNSUPPORTED					-12530 /* \"%s\" is not supported */

#define BG_ERR_INVALID_NUM_PARAM		    -12531 /* Invalid number parameter specified: %d */

#define BG_ERR_INVALID_STR_PARAM		    -12532 /* Invalid string parameter specified: %d */

#define BG_ERR_INVALID_WAIT_STATUS			-12533 /* Invalid status to wait for: %d */

#define BG_ERR_INVALID_SESSION				-12534 /* Invalid session handle provided */

#define BG_ERR_WAIT_TIMEOUT					-12535 /* Control operation has timed out */

#define BG_ERR_AGENT_NOT_RUNNING			-12536 /* Operation \"%s\" cannot be performed because sync agent is not running */

#define BG_ERR_TOO_MANY_READERS				-12537 /* Cannot create message reader because the allowed maximum of %d running readers will be exceeded */

#define BG_ERR_READER_CANCELED				-12538 /* Message reader was canceled from another thread */

#define BG_ERR_AGENT_DISABLED				-12539 /* Cannot start sync agent because it has been disabled */

#define BG_ERR_NO_BG_PUBS                   -12540 /* No background sync enabled publications were found on the client */

#define BG_ERR_RULE_EVAL_DB_LOCKED          -12541 /* Failed to evaluate rules for database \"%s\" because it is locked by an application */

#define BG_ERR_INVALID_PARAM		        -12542 /* Invalid parameter specified: %d */

#define BG_ERR_START						-12543 /* Failed to start sync agent (see the cause) */

#define BG_ERR_STOP							-12544 /* Failed to stop sync agent (see the cause) */

#define BG_ERR_PAUSE						-12545 /* Failed to pause sync agent (see the cause) */

#define BG_ERR_RESUME						-12546 /* Failed to resume sync agent (see the cause) */

#define BG_ERR_FATAL						-12547 /* Sync agent encountered fatal error or cannot be stopped */
