# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mFinity_HHI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mFinity_HHI

  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

end

target 'NotificationServiceHHI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationServiceHHI

end
