# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'korchampass' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for korchampass

  target 'korchampassTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'korchampassUITests' do
    # Pods for testing
  end

  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

end
